// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1avXdpd15-JN-G7UIwtj9Sc1fPE0vQ60',
    appId: '1:280200340012:web:08db33e2d872805584e789',
    messagingSenderId: '280200340012',
    projectId: 'note-app-defab',
    authDomain: 'note-app-defab.firebaseapp.com',
    storageBucket: 'note-app-defab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjWKq-1Dx3gV-60488MxoxY4bMlZ4GEM',
    appId: '1:280200340012:android:33d39fc89d69f74f84e789',
    messagingSenderId: '280200340012',
    projectId: 'note-app-defab',
    storageBucket: 'note-app-defab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqkBlHxYG34pQq9GyYX4RRzXWvNV3m3QA',
    appId: '1:280200340012:ios:eddbb929c9f3d13c84e789',
    messagingSenderId: '280200340012',
    projectId: 'note-app-defab',
    storageBucket: 'note-app-defab.appspot.com',
    iosClientId: '280200340012-ninlp8kpvbo0rumg9q8ssnbr5crb9drd.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqkBlHxYG34pQq9GyYX4RRzXWvNV3m3QA',
    appId: '1:280200340012:ios:236c1cdeeb929ea984e789',
    messagingSenderId: '280200340012',
    projectId: 'note-app-defab',
    storageBucket: 'note-app-defab.appspot.com',
    iosClientId: '280200340012-hqfrt3q5d1nftqejelernj36gqfg6llo.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
